path_to_1c: # путь до 1cv8.exe
path_to_com: # путь до comcntr.dll
server: # адрес сервера
dbname: # имя конфигурации 1С
login: # логин от учетки, с которой производится обмен
password: # пароль от учетки, с которой производится обмен
exchange_name: # имя плана обмена
parallel: # true - одновременное принятие и отправка всех обменов, false - последовательное

# Коды планов обмена
pdb: 
  - # Код плана

fpdb:
  - # Путь для очистки файлов обмена

suffixes:
  - # Суффикс файлов обмена для удаления после принятия